# Generated by Django 6.0.3 on 2026-03-20 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='討伐日')),
                ('count', models.PositiveIntegerField(verbose_name='配った枚数')),
                ('cast_name', models.CharField(blank=True, max_length=50, verbose_name='キャスト名')),
            ],
        ),
    ]
